Feature/item page
Regni/rently pull request #3
Opened 2024-12-09 01:03 UTC by jhn322

Item page 
- Grid layout som visar bild av item, title, price och owner från items.js
- Varje item visar en ny bild på hover
- Lagt till en Category knapp som kan filtrera bland kategorier, just nu går det att välja flera kategorier samtidigt. 
- Lagt till yttliggare 2 st item (item5, item6) och 2st exempel bilder per item i item.js för att testa grid UI.

***Det enda som kan bli konflikt är tillägget av nya bildlänkarna och item5 & item6 i items.js om nån annan har rört den filen.***

![Skärmbild 2024-12-09 015755](https://github.com/user-attachments/assets/0a838c76-5098-46f6-834c-019e170ff3ab)

2024-12-09 02:37 UTC, Regni commented on src/views/ItemsView.vue
> +})
You can remove this block and add `@click="isDropdownOpen = false"` to line 49 and `@click.stop` to line 54 and 57 to avoid propagation

2024-12-09 02:44 UTC, Regni requested changes
The currency is missing on the price but other than that I think it looks great. I really like the picture changing when you hover over the items. GJ!

I have added a comment on line 26 that we could consider changing but it is minor just less code to read.

2024-12-09 02:44 UTC, Regni commented on src/views/ItemsView.vue
> +            <p><strong>Price:</strong> {{ item.price }}</p>
The currency is missing

2024-12-09 10:04 UTC, EllenSandqvist approved these changes
Snyggt jobbat! Vad mycket du hunnit fixa.
Den enda funderingen jag har gäller @change="toggleCategory(category)" - ser inte att den funktionen är deklarerad någonstans, men det kanske är nåt som kommer sedan?

2024-12-09 19:12 UTC, jhn322 commented
> Snyggt jobbat! Vad mycket du hunnit fixa. Den enda funderingen jag har gäller @change="toggleCategory(category)" - ser inte att den funktionen är deklarerad någonstans, men det kanske är nåt som kommer sedan?

bra att du såg det, toggleCategory är en funktion från en tidigare lösning som inte funkade, glömde ta bort den.

2024-12-09 22:43 UTC, Regni requested changes

2024-12-09 22:43 UTC, Regni commented on src/views/ItemsView.vue
> +            <p><strong>Price:</strong> ${{ item.price }}</p>
```suggestion
            <p><strong>Price:</strong> {{ item.price }} kr</p>
```

2024-12-10 08:31 UTC, Regni approved these changes

2024-12-10 08:31 UTC, merged

2024-12-10 08:33 UTC, EthanHunt711 reviewed
ser bra ut